version: 2.1

jobs:
  build:
    shell: /bin/bash --login
    machine:
      # See https://circleci.com/docs/2.0/configuration-reference/#available-machine-images
      image: ubuntu-2004:202107-02
    steps:
      - run:
          name: Check Python
          command: |
            command -v python
            command -v pip
            python --version
            pip --version
      - run:
          name: Install dep
          command: |
             sudo pip install --index-url=https://pypi.python.org/simple/ nose

workflows:
  main:
    jobs:
      - build
