version: 2.1

jobs:
  build:
    shell: /bin/bash --login
    machine: true
    steps:
      - run:
          name: Check Python
          command: |
            command -v python
            command -v pip
            python --version
            pip --version
      - run:
          name: Install dep
          command: |
             # when using `sudo` for pip install, we see errors like this:
             # Downloading/unpacking nose
             # Cannot fetch index base URL https://pypi.python.org/simple/
             # Could not find any downloads that satisfy the requirement nose
             #
             # Opening the pip logs, I can see HTTP 403 errors due to SNI required, specifically:
             # Downloading/unpacking nose
             # Getting page https://pypi.python.org/simple/nose/
             # Could not fetch URL https://pypi.python.org/simple/nose/: 403 Client Error: SNI is required
             # Will skip URL https://pypi.python.org/simple/nose/ when looking for download links for nose
             # 
             # sudo pip install --index-url=https://pypi.python.org/simple/ nose
             #
             # I tried installing without sudo and it works well
             pip install --index-url=https://pypi.python.org/simple/ nose

workflows:
  main:
    jobs:
      - build
